calculator/urls.py
from django.urls import path, include
from calculator import views
from .views import calc
from rest_framework import routers

app_name = 'calculator'

router = routers.DefaultRouter()
router.register(r'faqs', views.FaqViewSet)

urlpatterns = [
    path('', views.calc, name='calc'),
    path('faq/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', 
    namespace='rest_framework')),
]

config/urls.py
from django.conf.urls import handler403, handler404, handler500
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings



urlpatterns = [
    # Django
    path('adm-cit-tree/', admin.site.urls), #Changed for admin-hardening

    # Favicon - from https://simpleit.rocks/python/django/django-favicon-adding/
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    
    # MS4
    path('', include('home.urls')),    
    path('accounts/', include('allauth.urls')),
    path('calculator/', include('calculator.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('donations/', include ('donations.urls', namespace='donations')),
    path('shop/', include ('shop.urls', namespace='shop')),
]

handler404 = 'home.views.custom_error_404'
handler403 = 'home.views.custom_error_403'
handler500 = 'home.views.custom_error_500'

donations/urls.py
from django.urls import path
from . import views
from .views import (DonateLandingPage,
                    CancelView,
                    SuccessView,
                    CreateCheckoutSessionView, 
                    stripe_webhook
                    )


app_name = 'donations'

urlpatterns = [
    path('', DonateLandingPage.as_view(), name="donate-landing"),
    #path('donations/create-checkout-session/', views.create_checkout_session, name ="create-checkout-session"),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('webhooks/stripe', stripe_webhook, name='stripe-webhook'),
]

home/urls.py
# Setup basedon Django for Professionals
from django.contrib import admin
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.IndexView.as_view(), name='projects'),
    path('updates/', views.UpdatesView.as_view(), name = 'updates'),
    path('updates/add/<slug:slug>', views.AddUpdateView.as_view(), name='add-update'),
    path('reports/<int:pk>/', views.ReportView.as_view(), name='report'),
    path('reports/<int:pk>/delete', views.DeleteReportView.as_view(), name='report-delete'),
    path('updates/<project>/', views.ProjectUpdatesView.as_view(), name='projupdates'),
    path('userupdates/', views.UserUpdatesView.as_view(), name='userupdates'),
    path('<slug:slug>/', views.SpotlightView.as_view(), name='spotlight'),
    path('<slug:slug>/edit', views.ProjectEditView.as_view(), name='project-edit'),
    ]

donations/models.py
from django.conf import settings
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User
from django.db.models.fields import CharField, DateField, DecimalField, EmailField

# Based on: https://justdjango.com/blog/django-stripe-payments-tutorial

class Donation(models.Model):
    name = models.CharField(max_length=100)
    stripe_product_id = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    

class Price(models.Model):
    donation = models.ForeignKey(Donation, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default = "desc")
    stripe_price_id = models.CharField(max_length=100)
    price = models.IntegerField(default=0)  #Note: Cents value

    def __str__(self):
        return self.description
	
    def get_display_price(self):
        return "{0:.2f}".format(self.price / 100) #Convert from cents to euros for display


class Donor(models.Model):
    donor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=CASCADE)
    amount = models.IntegerField(default=0)
    email_used = EmailField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.donor} on {self.date}"

donations/views.py
import stripe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model #https://learndjango.com/tutorials/django-best-practices-referencing-user-model
from django.core.mail import send_mail
from django.http.response import HttpResponse, JsonResponse
from django.conf import settings
from django.views.generic import TemplateView
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.views import View
from .models import Price, Donation, Donor

stripe.api_key = settings.STRIPE_SECRET_KEY

""" Code in this file relating to handling stripe payments and webhooks is from:
Stripe documentation eg: https://stripe.com/docs/payments/checkout/fulfill-orders
Tutorial 1: https://testdriven.io/blog/django-stripe-tutorial/
Tutorial 2: https://justdjango.com/blog/django-stripe-payments-tutorial """

class DonateLandingPage(LoginRequiredMixin,TemplateView):            
    template_name = "donations/donate.html"

    def get_context_data(self, **kwargs):
        donation = Donation.objects.get(name="Regular")
        prices = Price.objects.filter(donation=donation)
        context = super(DonateLandingPage,
                        self).get_context_data(**kwargs)
        context.update({
            "donation": donation,
            "prices": prices
        })
        return context


class SuccessView(TemplateView):
    template_name = "donations/success.html"


class CancelView(TemplateView):
    template_name = "donations/cancel.html"


class CreateCheckoutSessionView(View):
    def post(self, request, *args, **kwargs):
        DOMAIN = 'https://ms4-citizen-tree.herokuapp.com/donations/'
        price = Price.objects.get(id=self.kwargs["pk"])
        #client_reference_id=request.user.id if request.user.is_authenticated else None,
        #donor = request.user.username if request.user.is_authenticated else None,
        checkout_session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[
                {
                    'price': price.stripe_price_id,
                    'quantity': 1,
                },
            ],
            mode='payment',
            success_url= DOMAIN + 'success/',
            cancel_url= DOMAIN + 'cancel/',
            client_reference_id=request.user.id if request.user.is_authenticated else None,
            #metadata={'donor': 'request.user.username if request.user.is_authenticated else None'}
            #donor = request.user.username if request.user.is_authenticated else None             
        )
        #print (client_reference_id)
        return redirect(checkout_session.url)
    
    
@csrf_exempt
def stripe_webhook(request):
  endpoint_secret = settings.STRIPE_WH_SECRET
  payload = request.body
  sig_header = request.META['HTTP_STRIPE_SIGNATURE']
  event = None

  try:
    event = stripe.Webhook.construct_event(
      payload, sig_header, endpoint_secret
    )
  except ValueError as e:
    # Invalid payload
    return HttpResponse(status=400)
  except stripe.error.SignatureVerificationError as e:
    # Invalid signature
    return HttpResponse(status=400)

  # Handle the checkout.session.completed event
  if event['type'] == 'checkout.session.completed':
    session = event['data']['object']
    customer_email = session["customer_details"]["email"]
    amount = session["amount_total"]
    display_amount = "{0:.2f}".format(amount / 100)
    

    
    send_mail('Your donation', f'Thank you for your donation of {display_amount} euros to Citizen Tree.', 'ms4.citizentree@gmail.com', [customer_email], fail_silently=False)
    handle_checkout_session(session) # Based on: https://github.com/testdrivenio/django-stripe-checkout/blob/master/payments/views.py
    """
    Here:
    Add a row to a 'Received' model
    With: User, amount, date, 
    Received.objects.create(user=user, amount = display_amount, date = now,)

    do this by calling another function: handle_checkout_session(session) - see https://github.com/testdrivenio/django-stripe-checkout/blob/master/payments/views.py
    """
  return HttpResponse(status=200) 

def handle_checkout_session(session):
    # https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#referencing-the-user-model
    # https://learndjango.com/tutorials/django-best-practices-referencing-user-model

    User = get_user_model()
    # client_reference_id = user's id
    client_reference_id = session.get("client_reference_id")
    # payment_intent = session.get("payment_intent")

    if client_reference_id is None:
        """Customer wasn't logged in when purchasing - this shouldn't happen
        because the donate button is visible only to logged-in users - To do!""" 
        return

    # Customer was logged in we can now fetch the Django user and make changes to our models
    try:
        user = User.objects.get(id=client_reference_id)
        customer_email = session["customer_details"]["email"]
        amount = session["amount_total"]
        display_amount = "{0:.2f}".format(amount / 100)
        donor_user = user.username
        
        send_mail('Thank you for your donation', f'Hi there {donor_user}, thank you for your donation of {display_amount} euros to Citizen Tree.', 
        'ms4.citizentree@gmail.com', [customer_email], fail_silently=False)
        
        # Save the donation to the DB
        Donor.objects.create(
          donor = User.objects.get(id=client_reference_id),
          amount = amount,
          email_used=customer_email,
        )

    except User.DoesNotExist:
        pass

donations/templates/donations/cancel.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block extra_js %}

{% endblock %}

{% block extra_title %} - Donate{% endblock %}

{% block content %}
<div class="page-desc">
  <h1 class="index-h">Cancelling donation process to Citizen Tree</h1>
</div>
<section>
    <p>Don't want to donate right now?</p> 
      <p>No problem. Please feel free to contact us if you'd like more information on our activities and plans.</p>
  </section>


{% endblock %}

donations/templates/donations/donate.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block extra_js %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
{% endblock %}

{% block extra_title %} - Donate{% endblock %}

{% block content %}

<div class="page-desc">
    <h1 class="index-h">Donate to Citizen Tree</h1>
</div>
<section>
  <div class="donation">
      <div class="description">
          
          <hr />

          <div class="donations-block">

          <p>Donations are securely processed using Stripe. We do not collect or store your credit card details.</p>
          
            
          {% for price in prices %}

          <div class="donate-block-ind">
              <h5 class="index-h">€ {{ price.get_display_price }}</h5>
              <form action="{% url 'donations:create-checkout-session' price.id %}" method="POST">
                  {% csrf_token %}
                  <button class="btn-info" type="submit">Donate Now: €{{ price.get_display_price }} </button><br>
              </form>
          </div>

          {% endfor %}

          <div class="donate-block-info">
              <p>
                  See our <a href="{% url 'calculator:calc' %}">calculations page</a> for more information on:
                  <ul>
                      <li>How your donation will be used</li>
                      <li>How we estimate the potential impact from a CO2 perspective</li>
                      <li>How different tree-planting projects sequester at different rates</li>
                  </ul> 
              </p>
          </div>
          <div class="donate-block-info">
                <p>For more information on our various projects, check out our <a href="{% url 'projects:projects' %}">Projects</a> page.</p>
        </div>
      </div>
  </div>
</section>

{% endblock %}

donations/templates/donations/success.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block extra_js %}

{% endblock %}

{% block extra_title %} - Donate{% endblock %}

{% block content %}
<div class="page-desc">
  <h1 class="index-h">Donation was successful</h1>
</div>
<section>
    <p>Thanks for your donation to Citizen Tree. You will receive a confirmation email from us.</p>
    <p>We look forward to seeing you in person.</p>
  </section>


{% endblock %}