config/urls.py
from django.conf.urls import handler403, handler404, handler500
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings



urlpatterns = [
    # Django
    path('adm-cit-tree/', admin.site.urls), #Changed for admin-hardening

    # Favicon - from https://simpleit.rocks/python/django/django-favicon-adding/
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    
    # MS4
    path('', include('home.urls')),    
    path('accounts/', include('allauth.urls')),
    path('calculator/', include('calculator.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('donations/', include ('donations.urls', namespace='donations')),
    path('shop/', include ('shop.urls', namespace='shop')),
]

handler404 = 'home.views.custom_error_404'
handler403 = 'home.views.custom_error_403'
handler500 = 'home.views.custom_error_500'

home/urls.py
# Setup basedon Django for Professionals
from django.contrib import admin
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.IndexView.as_view(), name='projects'),
    path('updates/', views.UpdatesView.as_view(), name = 'updates'),
    path('updates/add/<slug:slug>', views.AddUpdateView.as_view(), name='add-update'),
    path('reports/<int:pk>/', views.ReportView.as_view(), name='report'),
    path('reports/<int:pk>/delete', views.DeleteReportView.as_view(), name='report-delete'),
    path('updates/<project>/', views.ProjectUpdatesView.as_view(), name='projupdates'),
    path('userupdates/', views.UserUpdatesView.as_view(), name='userupdates'),
    path('<slug:slug>/', views.SpotlightView.as_view(), name='spotlight'),
    path('<slug:slug>/edit', views.ProjectEditView.as_view(), name='project-edit'),
    ]

projects/models.py
from django.conf import settings #Necessary due to custom user model: https://learndjango.com/tutorials/django-best-practices-referencing-user-model
from django.db import models
from django.db.models.fields import BooleanField, CharField, DateField, DecimalField, EmailField
from django.db.models.fields.files import ImageField
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

# Class-based view for projects based on: https://www.youtube.com/watch?v=RwWhQTSV44Q

class Project(models.Model):
    title = models.CharField(max_length=150)
    description = models.TextField(null=False)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name = 'projects')
    slug = models.SlugField(max_length=100, unique=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)
    location = models.CharField(max_length=80)
    nursery = BooleanField(default=False)
    plantation = BooleanField(default=False)
    species = CharField(max_length=180, null=True)
    available_to_partner = BooleanField(default=True)
    area_ha = DecimalField(max_digits=3, decimal_places=2)
    project_lead = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    contact = EmailField()
    started = DateField()
    picture = models.FileField(upload_to='media/', default='media/default.jpg', blank=True)

    def get_absolute_url(self):
        return reverse('projects:spotlight', kwargs={'slug': self.slug})


    class Meta:
        ordering=['-published']


    def __str__(self):
        return self.title

class Update(models.Model):
    title = models.CharField(max_length=100, null=False)
    update_slug = models.SlugField(max_length=100, unique=False)
    text = models.TextField(null=False)
    short_text = models.TextField(max_length=150)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now=True)
    project = models.ForeignKey(Project, default='1', on_delete=models.CASCADE)
    picture = models.FileField(upload_to='media/', default='media/default-2.jpg', blank=True)



    def get_absolute_url(self):
        return reverse('projects:report', kwargs={"id":self.id})

    class Meta:
        ordering = ['-date_added']   


    def __str__(self):
        return self.title

projects/forms.py
from django import forms
from .models import Update, Project


class AddUpdate(forms.ModelForm):

    class Meta:
        model = Update
        fields = ('title', 'text', 'short_text', 'picture')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control'}),
            'short_text': forms.TextInput(attrs={'class': 'form-control'}),
        } 


#Form for updating the project details
class EditProject(forms.ModelForm):

    class Meta:
        model = Project
        fields = ('title', 'description', 'author', 'location', 'nursery', 'plantation',
                'species', 'available_to_partner', 'area_ha', 'started', 'picture')

projects/views.py
# from django.views.generic.detail import DetailView
from django.conf import settings
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import Project, Update
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import AddUpdate, EditProject
from django.template.defaultfilters import slugify
from django.contrib.auth.mixins import LoginRequiredMixin # For class-based views (as opposed to @loginrequired)


class IndexView(ListView):
    model = Project
    template_name = 'projects/projects.html'


class SpotlightView(DetailView):
    model = Project
    template_name = 'projects/projectspotlight.html'
    context_object_name = 'project'

class UpdatesView(ListView):
    model = Update
    template_name = 'projects/updates.html'

class ProjectUpdatesView(ListView):
    template_name = 'projects/updates_by_project.html'
    
    def get_queryset(self):
        self.project = get_object_or_404(Project, title=self.kwargs['project'])
        return Update.objects.filter(project=self.project)

class UserUpdatesView(ListView): #Credit: https://stackoverflow.com/questions/38471260/django-filtering-by-user-id-in-class-based-listview
    template_name = 'projects/updates_by_user.html'
    
    def get_queryset(self):
        return Update.objects.filter(author=self.request.user)

class ReportView(DetailView):
    model = Update
    template_name = 'projects/report.html'
    context_object_name = 'report'   


class DeleteReportView(DeleteView):
    model = Update
    template_name = 'projects/delete_update.html'
    context_object_name = 'report' 
    success_url = '../../updates'


class AddUpdateView(LoginRequiredMixin,CreateView):
    model = Update
    form_class = AddUpdate
    template_name = 'projects/add_update.html'
    success_url = '../../updates' 



# https://stackoverflow.com/questions/55556165/setting-model-user-to-request-user-with-createview-in-django-returns-null-value
    def form_valid(self, form):
        form.instance.author_id = self.request.user.pk
        form.instance.update_slug = slugify(form.instance.title)
        form.instance.project = Project.objects.get(slug = self.kwargs['slug'])
        messages.success(self.request, 'Your update was added successfully.')
        return super().form_valid(form) 


class ProjectEditView(UpdateView):
    model = Project
    form_class = EditProject
    template_name = 'projects/edit_project.html'
    success_url = '../../projects'

projects/templates/projects/add_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-7 col-md-6 my-auto">
            <h1 class="display-4 logo-font text-black">
                Citizen Tree
            </h1>
            <h2>{{ heading }}</h2>
            
            {% if user.is_authenticated %}
                <h3>User: {{ username }}</h3>
                <hr />
                Hi {{ user.email }}!
                <p><a href="{% url 'account_logout' %}">Log Out</a></p>
            {% else %}
                <p>You are not logged in</p>
                <a href="{% url 'account_login' %}">Log In</a>
                <a href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}    
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div>
            {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
        </div>
        <div class="col-12">
            <form method="post" enctype="multipart/form-data"> <!-- https://stackoverflow.com/questions/32423123/django-create-view-image-upload/32429092 -->
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit">
            </form>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/delete_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header %}
{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post">{% csrf_token %}
     
 
                <p>Are you sure you want to delete the update titled "{{ report.title }}"?</p>
                 
                 
                    <input type="submit" class="btn btn-warning" value="Yes, delete it">
                </form>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/edit_project.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-7 col-md-6 my-auto">
            <h1 class="display-4 logo-font text-black">
                Citizen Tree
            </h1>
            <h2>{{ heading }}</h2>
            
            {% if user.is_authenticated %}
                <h3>User: {{ username }}</h3>
                <hr />
                Hi {{ user.email }}!
                <p><a href="{% url 'account_logout' %}">Log Out</a></p>
            {% else %}
                <p>You are not logged in</p>
                <a href="{% url 'account_login' %}">Log In</a>
                <a href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}    
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12">
            <form method="post" enctype="multipart/form-data"> <!-- https://stackoverflow.com/questions/32423123/django-create-view-image-upload/32429092 -->
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit">
            </form>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/projects.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="page-desc">
            <h1 class="index-h">Citizen Tree Projects</h1>
        </div>
    </div>
</div>
<div class="album py-5 ">
<div class="container">
    <div class="row">
                {% for project in object_list %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img class="card-img-top project-list-card" src="{{ project.picture.url }}" alt="The project profile picture or default backup">
                    <div class="card-body">
                            <h4 class=""><a href="{{ project.get_absolute_url }}">{{ project.title }}</a></h4>
                            <p class="card-text">{{ project.description|truncatewords:5 }}</p> <!-- Update model to have a short_desc and include here -->
                    </div>
                    <div class="card-footer text-muted">
                        Location: {{ project.location }}
                      </div>    
                </div>


            </div>
        {% endfor %}    



    </div>
</div>        
</div>







{% endblock %}

projects/templates/projects/projectspotlight.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="page-desc">
            <h1 class="index-h">Citizen Tree - Project Details</h1>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 pt-5">
            <img class="card-img-top" src="{{ project.picture.url }}" alt="Seedling being planted">
            <div class="card-body">
                <h5 class="card-title">{{ project.title }}</h5>
                <p class="card-text">{{ project.description }}</p>
                
                <ul>
                    <li>This project started: {{ project.started }}</li>
                    <li>Location: {{ project.location }}</li>
                    <li>Area (ha): {{ project.area_ha }}</li>
                    <li>Species: {{ project.species }}</li>
                    <li>Ready to team Up: {{ project.available_to_partner }}</li>
                </ul>
                <a href="{% url 'projects:projupdates' project.title %}" class="btn btn-primary">See updates from this project</a>
                {% if user.is_authenticated and user.username == project.author.username %}
                   
                    <a href="{% url 'projects:add-update' project.slug %}" class="btn btn-primary">Add an update for this project</a>
                    <a href="{% url 'projects:project-edit' project.slug %}" class="btn btn-primary">Update project details</a>
                    
                {% endif %}

              </div>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/report.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="page-desc">
            <h1 class="index-h">Project Update</h1>
            <hr>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 pt-5">
            <img class="card-img-top" src=" {{ report.picture.url }} " alt="Image for the project update or default">
            <div class="card-body">
                <h5 class="card-title">{{ report.title }}</h5>
                <p class="card-text">{{ report.date_added }}</p>
                
                <p class="card-text"> {{ report.text }}</p>
                <a href="{% url 'projects:updates' %}" class="btn btn-primary">Back to All Updates</a>
                <a href="{% url 'projects:projupdates' report.project %}" class="btn btn-primary">Back to Updates for This Project</a>
                {% if user.is_authenticated and user.username == report.author.username %}
                <a href="{% url 'projects:report-delete' pk=report.id %}" class="btn btn-warning">Delete this Update</a>
                {% endif %}
              </div>
        </div>
    </div>
</div>

{% endblock %}

projects/templates/projects/updates.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="page-desc">
            <h1 class="index-h">Citizen Tree Project Updates</h1>
            <hr>
        </div>
        <section>
    </div>
</div>

<div class="container">
    <div class="row">
        <div>
            {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                  <li class="{{ message.tags }}">{{ message }}</li>
                {% endfor %}
              </ul>
            {% endif %}
        </div>
        {% for update in object_list %}
        <div class="card w-75">
            <div class="card-body">
              <h5 class="card-title">{{ update.title }}</a></h5>
              <p class="card-text">{{ update.short_text }}</p>
              <p class="card-text">Added by {{update.author}} on {{update.date_added}} for project {{update.project}}.</a></p>
              <a href="{% url 'projects:report' pk=update.id %}" class="btn btn-primary">View this update</a>
            </div>
          </div>
        {% endfor %}    
    </div>
</div>        








{% endblock %}

projects/templates/projects/updates_by_project.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="page-desc">
            <h1 class="index-h">Project Updates</h1>
            <hr>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for update in object_list %}
        <div class="card w-75">
            <div class="card-body">
              <h5 class="card-title">{{ update.title }}</a></h5>
              <p class="card-text">{{ update.short_text }}</p>
              <p class="card-text">Added by {{ update.author }} on {{update.date_added}}</p>
              <a href="{% url 'projects:report' pk=update.id %}" class="btn btn-primary">View this update</a>
            </div>
          </div>
        {% endfor %}    
    </div>
</div>        








{% endblock %}

projects/templates/projects/updates_by_user.html
{% extends "base.html" %}
{% load static %}

{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-7 col-md-6 my-auto">
            <h1 class="index-h">
                Citizen Tree
            </h1>
            <h2>{{ heading }}</h2>
            
            {% if user.is_authenticated %}
                <h3>User: {{ username }}</h3>
                <hr />
                Hi {{ user.email }}!
                <p><a href="{% url 'account_logout' %}">Log Out</a></p>
            {% else %}
                <p>You are not logged in</p>
                <a href="{% url 'account_login' %}">Log In</a>
                <a href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}    
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        {% for update in object_list %}
        <div class="card w-75">
            <div class="card-body">
              <h5 class="card-title">{{ update.title }}</a></h5>
              <p class="card-text">{{ update.short_text }}</p>
              <p class="card-text">Added by {{update.author }} on {{update.date_added}}</p>
              <a href="{% url 'projects:report' pk=update.id %}" class="btn btn-primary">View this update</a>
            </div>
          </div>
        {% endfor %}    
    </div>
</div>        








{% endblock %}