calculator/urls.py
from django.urls import path, include
from calculator import views
from .views import calc
from rest_framework import routers

app_name = 'calculator'

router = routers.DefaultRouter()
router.register(r'faqs', views.FaqViewSet)

urlpatterns = [
    path('', views.calc, name='calc'),
    path('faq/', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', 
    namespace='rest_framework')),
]

config/urls.py
from django.conf.urls import handler403, handler404, handler500
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings



urlpatterns = [
    # Django
    path('adm-cit-tree/', admin.site.urls), #Changed for admin-hardening

    # Favicon - from https://simpleit.rocks/python/django/django-favicon-adding/
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    
    # MS4
    path('', include('home.urls')),    
    path('accounts/', include('allauth.urls')),
    path('calculator/', include('calculator.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('donations/', include ('donations.urls', namespace='donations')),
    path('shop/', include ('shop.urls', namespace='shop')),
]

handler404 = 'home.views.custom_error_404'
handler403 = 'home.views.custom_error_403'
handler500 = 'home.views.custom_error_500'

donations/urls.py
from django.urls import path
from . import views
from .views import (DonateLandingPage,
                    CancelView,
                    SuccessView,
                    CreateCheckoutSessionView, 
                    stripe_webhook
                    )


app_name = 'donations'

urlpatterns = [
    path('', DonateLandingPage.as_view(), name="donate-landing"),
    #path('donations/create-checkout-session/', views.create_checkout_session, name ="create-checkout-session"),
    path('create-checkout-session/<pk>/', CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('success/', SuccessView.as_view(), name='success'),
    path('webhooks/stripe', stripe_webhook, name='stripe-webhook'),
]

home/urls.py
# Setup basedon Django for Professionals
from django.contrib import admin
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
]

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.IndexView.as_view(), name='projects'),
    path('updates/', views.UpdatesView.as_view(), name = 'updates'),
    path('updates/add/<slug:slug>', views.AddUpdateView.as_view(), name='add-update'),
    path('reports/<int:pk>/', views.ReportView.as_view(), name='report'),
    path('reports/<int:pk>/delete', views.DeleteReportView.as_view(), name='report-delete'),
    path('updates/<project>/', views.ProjectUpdatesView.as_view(), name='projupdates'),
    path('userupdates/', views.UserUpdatesView.as_view(), name='userupdates'),
    path('<slug:slug>/', views.SpotlightView.as_view(), name='spotlight'),
    path('<slug:slug>/edit', views.ProjectEditView.as_view(), name='project-edit'),
    ]

shop/urls.py
from django.urls import path
from . import views



app_name = 'shop'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-spotlight'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name = 'increase-qty'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name = 'decrease-qty'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name = 'remove-item'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/stripe/', views.StripePaymentView.as_view(), name='stripe-pay'),
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe-webhook'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path ('orders/<pk>/', views.OrderReview.as_view(), name='order-review'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<!-- Head content based on boutique ado -->
<head>
  <link rel="icon"href="{% static 'favicon.ico' %}">
    {% block meta %}
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% endblock %}

    {% block extra_meta %}
    {% endblock %}

    {% block corecss %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% endblock %}

    {% block extra_css %}
    {% endblock %}

    {% block corejs %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/3612e09a65.js" crossorigin="anonymous"></script>
        <!-- stripe -->
        <script src="https://js.stripe.com/v3/"></script>
    {% endblock %}

    {% block extra_js %}
    {% endblock %}

    <title>Citizen Tree {% block extra_title %}{% endblock %}</title>
  </head>
<body>
<!-- Navbar from Bootstrap with custom changes -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'home:index' %}">Citizen Tree</a>
      <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#ms4Nav" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse ms4-navbar-expand" id="ms4Nav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'home:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'home:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'projects:projects' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'calculator:calc' %}">Calculate</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'donations:donate-landing' %}">Donate</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'home:contact' %}">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:product-list' %}">Shop</a>
          </li>
          <li class="nav-item">
            <a class="nav-link site-cart" href="{% url 'shop:summary' %}"><span><i class="fas fa-shopping-cart"></i></span></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'shop:profile' %}">My Orders</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
<div class="container">
{% block content %}
{% endblock content %}
</div>
<!-- Footer -->
<div style="flex-grow: 1"></div>
    <footer id="ms4-footer" class="container-fluid">
      <div class="row">
        <div class="col-md-4 footer-element">
          <small>Give us a call, after 6pm (this is a volunteer-run operation):
            099 234 5678
          </small>
        </div>
        <div class="col-md-4 footer-element">
          <small>Helping people networks put carbon in the ground since 2021.</small> 
            <small>Trees have been at it a little while longer.</small>
        </div>
        <div class="col-md-4 footer-element">
          <a
            href="https://github.com/WorkingEdge/ms4_citizen_tree"
            target="_blank"
            ><span><i class="fab fa-github fa-2x"></i></span
          ></a>
          <a href="https://www.instagram.com/" target="_blank"
            ><span><i class="fab fa-instagram fa-2x"></i></span
          ></a>
        </div>
      </div>
    </footer>

<!-- MS4 JavaScript -->
<script src="{% static 'js/base.js' %}"></script>
{% block extra_page_specific_js %}
{% endblock %}
</body>
</html>