config/urls.py
from django.conf.urls import handler403, handler404, handler500
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings



urlpatterns = [
    # Django
    path('adm-cit-tree/', admin.site.urls), #Changed for admin-hardening

    # Favicon - from https://simpleit.rocks/python/django/django-favicon-adding/
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
    
    # MS4
    path('', include('home.urls')),    
    path('accounts/', include('allauth.urls')),
    path('calculator/', include('calculator.urls')),
    path('projects/', include('projects.urls', namespace='projects')),
    path('donations/', include ('donations.urls', namespace='donations')),
    path('shop/', include ('shop.urls', namespace='shop')),
]

handler404 = 'home.views.custom_error_404'
handler403 = 'home.views.custom_error_403'
handler500 = 'home.views.custom_error_500'

home/urls.py
# Setup basedon Django for Professionals
from django.contrib import admin
from django.urls import path
from .views import HomePageView, ContactView, AboutView

app_name = 'home'

urlpatterns = [
    path('', HomePageView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('about/', AboutView.as_view(), name='about'),
]

shop/urls.py
from django.urls import path
from . import views



app_name = 'shop'

urlpatterns = [
    path('', views.CartView.as_view(), name='summary'),
    path('shop/', views.ProductListView.as_view(), name='product-list'),
    path('shop/<slug>/', views.ProductDetailView.as_view(), name='product-spotlight'),
    path('increase-quantity/<pk>/', views.IncreaseQuantityView.as_view(), name = 'increase-qty'),
    path('decrease-quantity/<pk>/', views.DecreaseQuantityView.as_view(), name = 'decrease-qty'),
    path('remove-from-cart/<pk>/', views.RemoveFromCartView.as_view(), name = 'remove-item'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('payment/stripe/', views.StripePaymentView.as_view(), name='stripe-pay'),
    path('webhooks/stripe/', views.stripe_webhook_view, name='stripe-webhook'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path ('orders/<pk>/', views.OrderReview.as_view(), name='order-review'),
]

shop/forms.py
from django.contrib.auth import get_user_model
from django import forms
from .models import OrderItem, VarietySpec, Product, Address

User = get_user_model()

class AddToCartForm(forms.ModelForm):

    variety = forms.ModelChoiceField(queryset=VarietySpec.objects.none())
    quantity = forms.IntegerField(min_value=1)

    class Meta:
        model = OrderItem
        fields = OrderItemfields = ['quantity', 'variety']

    def __init__(self, *args, **kwargs):
        self.product_id = kwargs.pop('product_id')
        product = Product.objects.get(id=self.product_id)
        super().__init__(*args, **kwargs)

        self.fields['variety'].queryset = product.available_varieties.all()

    def clean(self):
        product_id = self.product_id
        product = Product.objects.get(id=self.product_id)
        quantity = self.cleaned_data['quantity']
        max_available = product.stock - 5
        if max_available < 0:
            print_max = 0
        else:
            print_max = max_available    

        if max_available < quantity:
            raise forms.ValidationError(f"Sorry, the most we can accept an order for at the moment is {print_max}. Please adjust your order.")
            



class AddressForm(forms.Form):
    
    shipping_address_line_1 = forms.CharField(required=False)
    shipping_address_line_2 = forms.CharField(required=False)
    shipping_address_county = forms.CharField(required=False)
    shipping_address_eircode = forms.CharField(required=False)

    billing_address_line_1 = forms.CharField(required=False)
    billing_address_line_2 = forms.CharField(required=False)
    billing_address_county = forms.CharField(required=False)
    billing_address_eircode = forms.CharField(required=False)

    selected_shipping_address = forms.ModelChoiceField(
        Address.objects.none(), required = False
    )
    selected_billing_address = forms.ModelChoiceField(
        Address.objects.none(), required = False
    )

    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        user=User.objects.get(id=user_id)

        shipping_address_queryset = Address.objects.filter(
        user=user,
        address_type='S',
        )
        billing_address_queryset = Address.objects.filter(
        user=user,
        address_type='B',
        )

        self.fields['selected_shipping_address'].queryset = shipping_address_queryset
        self.fields['selected_billing_address'].queryset = billing_address_queryset

    def clean(self):
        data = self.cleaned_data

        selected_shipping_address = data.get('selected_shipping_address', None)
        if selected_shipping_address is None:
            if not data.get('shipping_address_line_1', None):
                self.add_error("shipping_address_line_1", "Fill in this field")
            if not data.get('shipping_address_line_2', None):
                self.add_error("shipping_address_line_2", "Fill in this field")
            if not data.get('shipping_address_county', None):
                self.add_error("shipping_address_county", "Fill in this field")
            if not data.get('shipping_address_eircode', None):
                self.add_error("shipping_address_eircode", "Fill in this field")

        selected_billing_address = data.get('selected_shipping_address', None)
        if selected_billing_address is None:
            if not data.get('billing_address_line_1', None):
                self.add_error("billing_address_line_1", "Fill in this field")
            if not data.get('billing_address_line_2', None):
                self.add_error("billing_address_line_2", "Fill in this field")
            if not data.get('billing_address_county', None):
                self.add_error("billing_address_county", "Fill in this field")
            if not data.get('billing_address_eircode', None):
                self.add_error("billing_address_eircode", "Fill in this field")


class StripePaymentForm(forms.Form):
    selectedCard = forms.CharField(max_length=100)

shop/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
import stripe
import json
import os
import datetime
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import send_mail
from django.http.response import HttpResponse, JsonResponse
from django.conf import settings
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from django.views.generic.base import TemplateView
from stripe.api_resources import payment_intent

from home.models import Customer
from .models import Product, OrderItem, Address, StripePayment, Order
from .utils import get_or_set_order_session
from .forms import AddToCartForm, AddressForm, StripePaymentForm

stripe.api_key = settings.STRIPE_SECRET_KEY

User = get_user_model()

class ProductListView(generic.ListView):
    template_name = 'shop/product_list.html'
    queryset=Product.objects.all()


class ProductDetailView(generic.FormView):
    template_name = 'shop/product_spotlight.html'
    form_class = AddToCartForm


    def get_object(self):
        return get_object_or_404(Product, slug=self.kwargs["slug"])

    def get_success_url(self):
        return reverse("shop:summary") 

    def get_form_kwargs(self):
        kwargs = super(ProductDetailView, self).get_form_kwargs()
        kwargs["product_id"] = self.get_object().id
        return kwargs
    
    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        product = self.get_object() 

        item_filter = order.items.filter(
            product=product,
            variety = form.cleaned_data['variety'])

        if item_filter.exists():
            item = item_filter.first()
            item.quantity = int(form.cleaned_data['quantity'])
            item.save()

        else:
            new_item = form.save(commit=False)
            new_item.product = product
            new_item.order = order    
            new_item.save()

        return super(ProductDetailView, self).form_valid(form)


    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product'] = self.get_object()
        return context


class CartView(generic.TemplateView):
    template_name = 'shop/cart.html'

    def get_context_data(self, **kwargs):
        context = super(CartView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context  

class IncreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.quantity += 1
        order_item.save()
        return redirect("shop:summary")   


class DecreaseQuantityView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        if order_item.quantity <= 1:
            order_item.delete()
        else:
            order_item.quantity -= 1
            order_item.save()
        return redirect("shop:summary") 


class RemoveFromCartView(generic.View):
    def get(self, request, *args, **kwargs):
        order_item = get_object_or_404(OrderItem, id=kwargs['pk'])
        order_item.delete()
        return redirect("shop:summary") 


class CheckoutView(LoginRequiredMixin, generic.FormView):
    template_name = 'shop/checkout.html'
    form_class = AddressForm

    def get_success_url(self):
        return reverse("shop:stripe-pay")
    
    def form_valid(self, form):
        order = get_or_set_order_session(self.request)
        selected_shipping_address = form.cleaned_data.get('selected_shipping_address')
        selected_billing_address = form.cleaned_data.get('selected_billing_address')

        if selected_shipping_address:
            order.shipping_address = selected_shipping_address
        else:
            address = Address.objects.create(
                address_type='S',
                user = self.request.user,
                address_line_1=form.cleaned_data['shipping_address_line_1'],
                address_line_2=form.cleaned_data['shipping_address_line_2'],
                county=form.cleaned_data['shipping_address_county'],
                eircode=form.cleaned_data['shipping_address_eircode'],
            )
            order.shipping_address = address

        if selected_billing_address:
            order.billing_address = selected_billing_address
        else:
            address = Address.objects.create(
                address_type='B',
                user = self.request.user,
                address_line_1=form.cleaned_data['billing_address_line_1'],
                address_line_2=form.cleaned_data['billing_address_line_2'],
                county=form.cleaned_data['billing_address_county'],
                eircode=form.cleaned_data['billing_address_eircode'],
            )
            order.billing_address = address
        order.save()

        messages.info(self.request, "Addresses have been added successfully")
        return super(CheckoutView, self).form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super(CheckoutView, self).get_form_kwargs()
        kwargs["user_id"] = self.request.user.id
        return kwargs
    
    def get_context_data(self, **kwargs):
        context = super(CheckoutView, self).get_context_data(**kwargs)
        context["order"] = get_or_set_order_session(self.request)
        return context 

class StripePaymentView(generic.FormView):
    template_name = 'shop/stripe_payment.html'
    form_class = StripePaymentForm

    def form_valid(self, form):
        payment_method = form.cleaned_data["selectedCard"]
        print(payment_method)
        if payment_method != "newCard":
            try:
                order = get_or_set_order_session(self.request)
                payment_intent = stripe.PaymentIntent.create(
                    amount=order.get_raw_total(),
                    currency='eur',
                    customer=self.request.user.customer.stripe_customer_id,
                    payment_method=payment_method,
                    off_session=True,
                    confirm=True,
                )
                payment_record, created = StripePayment.objects.get_or_create(
                    order=order
                )
                payment_record.payment_intent_id = payment_intent["id"]
                payment_record.amount = order.get_total()
                payment_record.save()


            except stripe.error.CardError as e:
                err = e.error
                # Error code will be authentication_required if authentication is needed
                print("Code is: %s" % err.code)
                payment_intent_id = err.payment_intent['id']
                payment_intent = stripe.PaymentIntent.retrieve(
                    payment_intent_id)
                messages.warning(self.request, "Code is: %s" % err.code)
        return redirect("shop:profile")

    def get_context_data(self, **kwargs):
        user = self.request.user
        if not user.customer.stripe_customer_id:
            stripe_customer = stripe.Customer.create(email=user.email)
            user.customer.stripe_customer_id = stripe_customer["id"]
            user.customer.save()

        order = get_or_set_order_session(self.request)

        payment_intent = stripe.PaymentIntent.create(
            amount=order.get_raw_total(), #Amount in cents
            currency='eur',
            customer=user.customer.stripe_customer_id,
            receipt_email = user.email #Stripe will send receipt (but not in test mode)
        )
        print(payment_intent)
        payment_record, created = StripePayment.objects.get_or_create(
            order=order
        )
        payment_record.payment_intent_id = payment_intent["id"]
        payment_record.amount = order.get_total()
        payment_record.save()

        cards = stripe.PaymentMethod.list(
            customer=user.customer.stripe_customer_id,
            type="card",
        )
        pay_methods=[]
        for card in cards:
            pay_methods.append(card["id"])

        print(cards)

        context = super(StripePaymentView, self).get_context_data(**kwargs)
        context ["order"] = get_or_set_order_session(self.request)
        context["STRIPE_PUBLIC_KEY"] = settings.STRIPE_PUBLIC_KEY
        context["client_secret"] = payment_intent["client_secret"]
        context["payment_methods"] = pay_methods
        return context

@csrf_exempt
def stripe_webhook_view(request):
    endpoint_secret = settings.STRIPE_WH_SECRET_SHOP
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the event
    if event.type == 'payment_intent.succeeded':
        payment_intent = event.data.object  # contains a stripe.PaymentIntent
        stripe_payment = StripePayment.objects.get(
            payment_intent_id=payment_intent["id"],
        )
        stripe_payment.successful = True
        stripe_payment.save()
        order = stripe_payment.order
        order.ordered = True
        order.ordered_date = timezone.now()
        order.save()
        handle_stock(order)
    else:
        # Unexpected event type
        return HttpResponse(status=400)

    return HttpResponse(status=200)

def handle_stock(ordered):
    sold = OrderItem.objects.filter(order = ordered)
    print(sold)
    for item in sold:
        qty_sold = item.quantity

shop/templates/shop/cart.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-12 col-md-6 my-auto">
            <h1 class="index-h">
                Citizen Tree - Your Cart
            </h1>
            
            
            {% if user.is_authenticated %}
                <h3 class="index-h">User: {{ user.username }}</h3>
                <hr />
                <p><a href="{% url 'account_logout' %}">Log Out</a></p>
            {% else %}
                <p>You are not logged in</p>
                <a href="{% url 'account_login' %}">Log In</a>
                <a href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}    
        </div>
    </div>
</div> 
<div class="cart-section">
<div class="container"> 
    <div class="row mb-5">
        <div class="col-md-12">
            <div class="cart-table">
                <table class="cart-table table table-reponsive">
                    <tbody>
                    <tr>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>Total</th>
                        <th>Actions</th>
                    </tr>
                        {% for item in order.items.all %}
                        <tr> 
                            <td class="product-thumbnail"><img src="{{ item.product.picture.url }}" alt="product image" class="img-fluid"></td>

                            <td class="product-name">
                                
                                <p>{{ item.product.title }}</p> 
                                <small>{{ item.variety.name }}</small>
                            </td>

                            <td>€{{ item.product.get_display_price }}</td>
                            
                            <td>
                                <div class="input-group mb-3 cart-input">
                                    <div class="input-group-prepend">
                                        <a href="{% url 'shop:decrease-qty' item.id %}" class = "btn btn-light"> &minus; </a>
                                    </div>
                                <input type="text" class="form-control text-center cart-qty" value="{{ item.quantity }}">
                                    <div class="input-group-append">
                                        <a href="{% url 'shop:increase-qty' item.id %}" class = "btn btn-light" style="max-width: 120px;"> &plus; </a>
                                    </div>
                                </div>
                            </td>
                            
                            <td>€{{ item.get_total_item_price_display }}</td>
                            
                            <td><a href=" {% url 'shop:remove-item' item.id %}" class="btn btn-warning btn-sm"><span><i class="fas fa-trash"></i></span></a></td>
                        </tr> 
                        {% empty %}
                        <tr>
                            <td colspan="6">Looks like your cart is empty. <a href="{% url 'shop:product-list' %}">Click here to order trees.</a> </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
              </div>

            {% if order.items.count > 0 %}    
              <div class="row">
                  <div class="col-md-6">
                      <div class="row mb-5">
                          <div class="col-md-12 text-center btn btn-info">
                              <a href="{% url 'shop:product-list' %}">Continue Shopping</a>
                          </div>
                      </div>
                  </div>

                  <div class="col-md-6 pl-5">
                      <div class="row justify-content-end">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12 text-right border-bottom mb-5">
                                    <h3 class="index-h">Cart Totals</h3>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span><h5 class="index-h">Subtotal</h5></span>
                                </div>
                                <div class="col-md-6 text-right text-white">
                                    <strong>€{{ order.get_subtotal }}</strong>
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-md-6">
                                    <span><h5 class="index-h">Delivery*</h5></span>
                                    <small class="text-white">*Flat fee for all orders.</small>
                                </div>
                                <div class="col-md-6 text-right text-white">
                                    <strong>€25.00</strong>
                                </div>
                            </div>
                            <div class="row mb-5">
                                <div class="col-md-6">
                                    <span><h5 class="index-h">Total</h5></span>
                                </div>
                                <div class="col-md-6 text-right text-white">
                                    <strong>€{{ order.get_total }}</strong>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <a href="{% url 'shop:checkout' %}" class="btn btn-info btn-block">Go to Checkout</a>
                                </div>
                            </div>

                        </div>

                      </div>
                  </div>



              </div>
              {% endif %}

        </div>
    </div>
    </div>
</div>

{% endblock %}

shop/templates/shop/checkout.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-12 col-md-6 my-auto">
            <h1 class="index-h">
                Citizen Tree - Checkout
            </h1>
            {% if user.is_authenticated %}
            <h3 class="index-h">User: {{ user.username }}</h3>
            <hr />
            <p><a href="{% url 'account_logout' %}">Log Out</a></p>
            {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'account_login' %}">Log In</a>
            <a href="{% url 'account_signup' %}">Sign Up</a>
            {% endif %}
        </div>
    </div>
</div>
<div class="cart-section">
    <div class="container">

        {% if not request.user.is_authenticated %}
        <div class="row mb-5"></div>
        <div class="col-md-12">
            <p>To complete the checkout process, you need to log in or sign up. <a href="{% url 'account_login' %}">log
                    in</a> or <a href="{% url 'account_signup' %}">sign up</a>.</p>
        </div>
        {% else %}
        <form method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-6 mb-5 mb-md-0">
                    <h3 class="index-h">Billing Details</h3>
                    <hr>
                    <div class="p-2 p-lg-2 text-white">
                        {{ form|crispy }}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-info btn-block">Go to Payment</button>
                    </div>

                </div>
                <div class="col-md-6">
                    <div class="row mb-5">
                        <div class="col-md-12">
                            <h3 class="index-h text-center mb-3">Your Order</h3>
                            
                            <div>
                                <table class="cart-table table table-reponsive">
                                    <tbody>
                                        <tr>                                       
                                        <th>Product</th>
                                        <th>Total</th> 
                                        {% for item in order.items.all %}                                       
                                    </tr>
                                        <tr> 
                                            <td class="product-name"> 
                                                <p>{{ item.product.title }} (<small>{{ item.variety.name }}</small>) x {{ item.quantity }}</p> 
                                                
                                            </td>
                                            <td>€{{ item.get_total_item_price_display }}</td>                                            
                                        </tr> 
                                        {% endfor %}

                                        <tr>
                                            <td><strong>Subtotal</strong></td>
                                            <td><strong>€{{ order.get_subtotal }}</strong></td>
                                        </tr>
                                        <tr>
                                            <td><strong>Total incl. delivery</strong></td>
                                            <td><strong>€{{ order.get_total }}</strong></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </form>

    </div>
    {% endif %}
</div>

<!-- {% if order.items.count > 0 %}
<div class="row">
    <div class="col-md-6">
        <div class="row mb-5">
            <div class="col-md-12 text-center btn btn-info">
                <a href="{% url 'shop:product-list' %}">Continue Shopping</a>
            </div>
        </div>
    </div>

    <div class="col-md-6 pl-5">
        <div class="row justify-content-end">
            <div class="col-md-12">
                <div class="row">
                    <div class="col-md-12 text-right border-bottom mb-5">
                        <h3 class="index-h">Cart Totals</h3>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <span>
                            <h5 class="index-h">Subtotal</h5>
                        </span>
                    </div>
                    <div class="col-md-6 text-right text-white">
                        <strong>€{{ order.get_subtotal }}</strong>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-md-6">
                        <span>
                            <h5 class="index-h">Delivery*</h5>
                        </span>
                        <small class="text-white">*Flat fee for all orders.</small>
                    </div>
                    <div class="col-md-6 text-right text-white">
                        <strong>€25.00</strong>
                    </div>
                </div>
                <div class="row mb-5">
                    <div class="col-md-6">
                        <span>
                            <h5 class="index-h">Total</h5>
                        </span>
                    </div>
                    <div class="col-md-6 text-right text-white">
                        <strong>€{{ order.get_total }}</strong>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <a href="{% url 'shop:checkout' %}" class="btn btn-info btn-block">Go to Checkout</a>
                    </div>
                </div>

            </div>

        </div>
    </div>



</div>
{% endif %} -->

</div>
</div>
</div>
</div>

{% endblock %}

shop/templates/shop/product_spotlight.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header %}
{% endblock %}

{% block content %}

<div class="container h-100">
    <div class="row h-100">
        <div class="col-7 col-md-6 my-auto">
            <div class="page-desc">
                <h1 class="index-h">Citizen Tree - Shop</h1>
            </div>    
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-12 pt-5">
            <img class="card-img-top" src="{{ product.picture.url }}" alt="Product picture">
            <div class="card-body">
                <h5 class="card-title">{{ product.title }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <br>
                <p>Note: Our current stock is approximately {{product.stock}}. We will do our best to meet your specific variety requirements. If we can't, we'll get in touch before sending an alternative, for example, might be able to send a Bardsey variety apple tree instead of a Discovery.</p>

                {% if product.in_stock %}
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}       

                    <button class="btn btn-sm btn-primary" type="submit">Add to Cart</button>
                </form>
                {%else%}
                <p>Sorry, our stock of '{{ product.title }}' is too low to take an order online.</p>
                {%endif%}
                <br>
                <div class="btn btn-sm btn-primary">
                <a href="{% url 'shop:product-list' %}">Back to Shop</a>
            </div>
              </div>
        </div>
    </div>
</div>

{% endblock %}